config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :user_types, only: [:new, :create, :show]
  devise_for :companies
  resources :organizations, only: [:new, :create, :show]
  devise_for :users
  resource :dashboard, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#index"
  resources :projects, only: [:index, :show]
  resources :schedules, only: [:index, :show]
  resources :events
  resources :crews, only: [:index, :show]
  resources :tasks, only: [:index, :show]
  resources :equipment, only: [:index, :show]
  resources :my_groups, only: [:index, :show]
  namespace :admin do
    resources :projects, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :schedules, only: [:new, :create, :show]
    resources :tasks, only: [:new, :create, :edit, :update, :destroy]
    resources :crews, only: [:new, :create, :edit, :update, :destroy]
    resources :equipment, only: [:new, :create, :edit, :update, :destroy]
    resources :my_groups, only: [:new, :create]
  end
  namespace :schedule do
    resources :tasks, only: [:update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :user

  validates :title, presence: true



end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :user

  validates :title, presence: true


end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/my_group.rb
class MyGroup < ApplicationRecord
  belongs_to :user
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :users
  
  
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :schedules
  belongs_to :user

  
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :project

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_many :tasks
  has_many :equipment
  has_many :crews
  has_many :my_groups
  belongs_to :organization, :optional => true

  accepts_nested_attributes_for :organization
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_type.rb
class UserType < ApplicationRecord
  
end

app/controllers/admin/schedules_controller.rb
class Admin::SchedulesController < ApplicationController
  before_action :authenticate_user!

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.create(schedule_params)
    if @schedule.valid?
      redirect_to schedules_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  private

  def schedule_params
    params.require(:schedule).permit(:project_id, :location, :lot_count)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
    @tasks = Task.all
    @crews = Crew.all
    @equipment = Equipment.all
    @projects = Project.all
    @events = Event.all
  end 
end

app/helpers/admin/schedules_helper.rb
module Admin::SchedulesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/my_groups_helper.rb
module MyGroupsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/views/schedules/index.html.erb
<script>
  $(function() {
    $('.tasks').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() } }
        });
      }
    });
  });

  $(function() {
    $('.crews').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() } }
        });
      }
    });
  });

  $(function() {
    $('.equipment').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() } }
        });
      }
    });
  });
</script>


<br />


<div class="booyah-box col-12">
  <h1 class="text-center">SCHEDULE</h1>
  <hr />   
  <h8><%= link_to 'Add Schedule', new_admin_schedule_path, class: 'nav-link' %></h8> 
  <!-- <div id="calendar"></div> -->
    <% @schedules.each do |schedule| %>
      <div class="row">
        <div class="booyah-box col-3 left" id="projectSchedules">
        
          <h3 class="text-left"><%= schedule.project.job_name %></h3>

          <h7 class="text-left"><b>Location:</b> <%= schedule.location %></h7><br>
          <h7 class="text-left"><b>Lot Count:</b> <%= schedule.lot_count %></h7>
        </div>
        <div class="booyah-box col-9">
          <%= week_calendar number_of_weeks: 1 do |date| %>
            <%= date %>
          <% end %>
        </div>
      </div>
      <br>
    <% end %>
  
</div>
<br>
<div class="booyah-box col-12">
  
  <div class="booyah-box col-12" id="calendarEvents">
    <div><h4 class="left">TASKS: </h4></div>
      <ul class="tasks">
      <% @tasks.each do |task| %>
        <li id="drag" data-item-id="<%= schedule_task_path(task) %>">
          <b><%= task.title %></b>
          -
          <%= task.description %>
        </li>
      <% end %>
    </ul>
    <br>
    <h8><%= link_to 'Add Task', new_admin_task_path, class: 'nav-link' %></h8>
  </div>
  <div class="booyah-box col-12" id="calendarEvents">
    <div><h4 class="left">CREWS: </h4></div>
      <ul class="crews">
        <% @crews.each do |crew| %>

          <li id="drag" >
            <b><%= crew.title %></b>
            -
            <%= crew.description %>
          </li>
        <% end %>
      </ul>
    <br>
    <h8><%= link_to 'Add Crew', new_admin_crew_path, class: 'nav-link' %></h8>
  </div>
  <div class="booyah-box col-12" id="calendarEvents">
    <div><h4 class="left">Equipment: </h4></div>
    <ul class="equipment">
        <% @equipment.each do |equipment| %>

          <li id="drag"">
            <b><%= equipment.title %></b>
            -
            <%= equipment.description %>
          </li>
        <% end %>
      </ul>
    <br>
    <h8><%= link_to 'Add Equipment', new_admin_equipment_path, class: 'nav-link' %></h8>
  </div>
  <!-- <div class="booyah-box col-12">
    <h4 class="left">MY GROUPS:</h4>
    <br>
  </div> -->
</div>
<br>
<!-- <div class="booyah-box col-12">
  <h4 class="left">CONFLICTS:</h4>
  <br>
</div> -->

<script type="text/javascript">
  $(document).ready(function() {
    $("#calendar").fullCalendar();
  });
</script>