config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :user_types, only: [:new, :create, :show]
  devise_for :companies
  resources :organizations, only: [:new, :create, :show]
  devise_for :users
  resource :dashboard, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "static_pages#index"
  resources :projects, only: [:index, :show]
  resources :schedules, only: [:index, :show]
  resources :events
  resources :crews, only: [:index, :show]
  resources :tasks, only: [:index, :show]
  resources :equipment, only: [:index, :show]
  resources :my_groups, only: [:index, :show]
  namespace :admin do
    resources :projects, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :schedules, only: [:new, :create, :show]
    resources :tasks, only: [:new, :create, :edit, :update, :destroy]
    resources :crews, only: [:new, :create, :edit, :update, :destroy]
    resources :equipment, only: [:new, :create, :edit, :update, :destroy]
    resources :my_groups, only: [:new, :create]
  end
  namespace :schedule do
    resources :tasks, only: [:update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :user

  validates :title, presence: true



end

app/models/equipment.rb
class Equipment < ApplicationRecord
  belongs_to :user

  validates :title, presence: true


end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/my_group.rb
class MyGroup < ApplicationRecord
  belongs_to :user
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :users
  
  
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :schedules
  belongs_to :user

  
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :project

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_many :tasks
  has_many :equipment
  has_many :crews
  has_many :my_groups
  belongs_to :organization, :optional => true

  accepts_nested_attributes_for :organization
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_type.rb
class UserType < ApplicationRecord
  
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  before_action :authenticate_user!

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.create(project_params)
    if @project.valid?
      redirect_to admin_project_path(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find_by_id(params[:id])
    if @project.blank?
      render plain: 'Not Found :(', status: :not_found
    end
  end

  def update
    @project = Project.find_by_id(params[:id])
    return render_not_found if @project.blank?

    @project.update_attributes(project_params)

    if @project.valid?
      redirect_to root_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project = Project.find_by_id(params[:id])
    return render_not_found if @project.blank?
    @project.destroy
    redirect_to root_path
  end

  private

  def project_params
    params.require(:project).permit(:job_name,:builder,:lots,:supervisor,:our_super,:phone,:email,:address,:city,:state,:zip)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find_by_id(params[:id])
    if @project.blank?
      render plain: 'Not Found :(', status: :not_found
    end
  end



  def self.initialize
      @api_key = "34ea9f2f4846a435ad387c86d9da5ba9"
      @api_base_url = "https://api.openweathermap.org/data/2.5/weather?"
    end

    def self.get_weather(zip)
      response = RestClient.get("#{@api_base_url}zip=#{zip},us&appid=#{@api_key}")
      JSON.parse(response)['weather'][0]['description']

    end

    def self.get_temp(zip)
      response = RestClient.get("#{@api_base_url}zip=#{zip},us&appid=#{@api_key}")
      data = JSON.parse(response)['main']['temp']
      data = ((data - 273.15) * (9/5)) + 32

    end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/my_groups_helper.rb
module MyGroupsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/views/admin/projects/edit.html.erb
<%= simple_form_for @equipment do |f| %>
  <div class="row">
      <div class="col-6">
        <%= f.input :builder %>
        <%= f.input :job_name %>
        <%= f.input :our_super %>
        <%= f.input :address %>
        <%= f.input :city %>
        <%= f.input :state %>
      </div>
      <div class="col-6">
        <%= f.input :zip %>
        <%= f.input :supervisor %>
        <%= f.input :email %>
        <%= f.input :phone %>
        <%= f.input :lots %>
      </div>
    </div>

    <%= f.submit %>
<% end %>

app/views/admin/projects/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new project</h1>
  <%= simple_form_for @project, url: admin_projects_path do |f| %>
    <div class="row">
      <div class="col-6">
        <%= f.input :builder %>
        <%= f.input :job_name %>
        <%= f.input :our_super %>
        <%= f.input :address %>
        <%= f.input :city %>
        <%= f.input :state %>
      </div>
      <div class="col-6">
        <%= f.input :zip %>
        <%= f.input :supervisor %>
        <%= f.input :email %>
        <%= f.input :phone %>
        <%= f.input :lots %>
      </div>
    </div>
    
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
    <% if @project.errors.any? %>
    <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>
  <% end %>
  <br>
</div>

app/views/admin/projects/show.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= @project.job_name %></h1>
  </div>

app/views/projects/index.html.erb
<br>
<% @projects.each do |project| %>
  <h2 class="text-center"><%= project.job_name %></h2>
  <br />
  <div class="row">
    <div class="col-sm-8 col-12">
      <%= project.user_id %>
    </div>
    <div class="col-sm-4 col-12 text-center">
      <%= link_to 'Button', '#', class: 'btn btn-primary btn-large' %>
    </div>
  </div>
  <br class="clr" />
<% end %>

app/views/projects/show.html.erb
<div class="booyah-box col-10 offset-1">
  <br>
  <h2 class="text-center project-info"><%= @project.builder %> - <%= @project.job_name %>
  <br>
  <br>
  <div class="row text-left">
      <div class="col-6">
        <h6><b>Address:</b> <%= @project.address %></h6>
        <h6><b>City:</b> <%= @project.city %></h6>
        <h6><b>State:</b> <%= @project.state %></h6>
        <h6><b>Zip:</b> <%= @project.zip %></h6>
        <h6><b>Lots:</b> <%= @project.lots %></h6>
      </div>
      <div class="col-6">
        <h6><b>Builder Super:</b> <%= @project.supervisor %></h6>
        <h6><b>Email:</b> <%= @project.email %></h6>
        <h6><b>Phone:</b> <%= @project.phone %></h6>
        <h6><b>Our Super:</b> <%= @project.our_super %></h6>
      </div>
  </div>
  <br class="clear">
  
    <div class="row col-12" id="weather-heading">
      <h4 style="text-align:center">Weather</h4>
    </div>
    <div class="row">

      <div class="col-6">
        <h6 style="text-align:left; float:left; float:center;"><b>Temp: </b></h6>
        <h6 style="text-align:left; float:left;" id="temperature">0.0</h6>
        <h6 style="text-align:left; float:left;" id="tempSymb">°F</h6>
      </div>
      <div class="col-6">
        <h6 style="text-align:left; float:left;"><b>Weather: </b></h6>
        <h6 style="text-align:left; float:left;" id="weather">Nil</h6>
      </div>

    </div>

</div>

<script type="text/javascript">
  const zip1 = '95811'

  function getTemp(zip, callback) {
    const path = 'https://api.openweathermap.org/data/2.5/weather?zip=' + zip + ',us&appid=34ea9f2f4846a435ad387c86d9da5ba9'
    fetch(path).then((res) => {
      return res.json()
    }).then((json) => {
      console.log(json)
      console.log(json.main.temp)
      callback(json)
    }).catch((err) => {
      console.log(err.message)
    })
    
  }

  function getWeather(zip, callback) {
    const path = 'https://api.openweathermap.org/data/2.5/weather?zip=' + zip + ',us&appid=34ea9f2f4846a435ad387c86d9da5ba9'
    fetch(path).then((res) => {
      return res.json()
    }).then((json) => {
      console.log(json)
      console.log(json.weather[0].description)
      callback(json)
    }).catch((err) => {
      console.log(err.message)
    })
    
  }

      const temperatureDisplay = document.getElementById('temperature')
      const weatherDisplay = document.getElementById('weather')
      
      const apikey = '34ea9f2f4846a435ad387c86d9da5ba9'
      getTemp(zip1, (json) => {
        temperatureDisplay.innerHTML = Math.floor(((json.main.temp - 273.15) * (9/5)) +32);
      })

      getWeather(zip1, (json) => {
        weatherDisplay.innerHTML = json.weather[0].description
      })

</script>